description = ""
title = "一体式"

[mongodb.development]
host = "127.0.0.1"
password = "123456"
port = 27017
username = "admin"

[perforces]

[perforce.development]
password = "Qaz12345"
port = "p4.com:2003"
username = "houankun"

[perforce.production.x51]
password = "oa_liangce"
port = "p4.com:2003"
username = "houankun"

[perforce.production.x52]
password = "oa_liangce"
port = "p4.com:2004"
username = "houankun"
